name: Basic Pipeline

on:
  push:
    branches:
      - main
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Check AWS CLI
        run: aws --version

      - name: Launch EC2
        run: |
          INSTANCE_ID=$(aws ec2 run-instances \
            --image-id ami-035827357e3c7e810 \
            --instance-type t3.micro \
            --key-name github-key \
            --security-group-ids sg-0d67bd2d0a09d9dfc \
            --subnet-id subnet-01a0c72ddd872c2b9 \
            --region ap-south-1 \
            --query 'Instances[0].InstanceId' \
            --output text)
          echo "INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_ENV




      - name: Wait before ec2 creation
        run: |
          echo "Waiting 30 seconds "
          sleep 30

      - name: Get EC2 public IP
        run: |
          PUBLIC_IP=$(aws ec2 describe-instances \
            --instance-ids "$INSTANCE_ID" \
            --query 'Reservations[0].Instances[0].PublicIpAddress' \
            --output text)

           echo "EC2_HOST=$PUBLIC_IP" >> $GITHUB_ENV

           echo "EC2 IP: $PUBLIC_IP"    


      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh

          echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
      - name: Copy index.html to server
        run: |
          scp -o StrictHostKeyChecking=no \
            -i ~/.ssh/id_ed25519 \
            index.html \
            "ec2-user@${{ env.EC2_HOST }}:/tmp/index.html"    



      - name: Install and start Nginx SSH
        run: |
          ssh -o StrictHostKeyChecking=no \
            -i ~/.ssh/id_ed25519 \
            "ec2-user@${{ env.EC2_HOST }}" \
            "sudo dnf update -y && \
             sudo dnf install -y nginx && \
             sudo mv /tmp/index.html /usr/share/nginx/html/index.html && \
             
             sudo systemctl enable nginx && \
             sudo systemctl start nginx"  



     